const LaptopProducts = [
    {
        id: 1,
        image: "https://via.placeholder.com/300",
        price: 150000,
        title: "MacBook Pro 16",
        description: "16-inch Retina display, M1 Pro chip, 16GB RAM, and 512GB SSD.",
        rating: 4.8,
        reviews: 5000,
        link: "#",
    },
    {
        id: 2,
        image: "https://via.placeholder.com/300",
        price: 120000,
        title: "Dell XPS 15",
        description: "15.6-inch 4K OLED display, Intel i7, 16GB RAM, and 1TB SSD.",
        rating: 4.7,
        reviews: 3800,
        link: "#",
    },
    {
        id: 3,
        image: "https://via.placeholder.com/300",
        price: 110000,
        title: "HP Spectre x360",
        description: "13.3-inch FHD touchscreen, Intel i7, 16GB RAM, and 512GB SSD.",
        rating: 4.6,
        reviews: 3200,
        link: "#",
    },
    {
        id: 4,
        image: "https://via.placeholder.com/300",
        price: 98000,
        title: "Asus ROG Zephyrus G14",
        description: "14-inch QHD display, AMD Ryzen 9, RTX 3060, 16GB RAM, 1TB SSD.",
        rating: 4.7,
        reviews: 4100,
        link: "#",
    },
    {
        id: 5,
        image: "https://via.placeholder.com/300",
        price: 140000,
        title: "Razer Blade 15",
        description: "15.6-inch FHD 240Hz, Intel i7, RTX 3070, 16GB RAM, 1TB SSD.",
        rating: 4.5,
        reviews: 3000,
        link: "#",
    },
    {
        id: 6,
        image: "https://via.placeholder.com/300",
        price: 85000,
        title: "Lenovo ThinkPad X1 Carbon",
        description: "14-inch FHD display, Intel i7, 16GB RAM, 512GB SSD, business laptop.",
        rating: 4.6,
        reviews: 2900,
        link: "#",
    },
    {
        id: 7,
        image: "https://via.placeholder.com/300",
        price: 92000,
        title: "Acer Predator Helios 300",
        description: "15.6-inch FHD 144Hz, Intel i7, RTX 3060, 16GB RAM, 512GB SSD.",
        rating: 4.4,
        reviews: 2700,
        link: "#",
    },
    {
        id: 8,
        image: "https://via.placeholder.com/300",
        price: 72000,
        title: "MSI GF65 Thin",
        description: "15.6-inch 144Hz, Intel i5, RTX 3060, 16GB RAM, 512GB SSD.",
        rating: 4.3,
        reviews: 2500,
        link: "#",
    },
    {
        id: 9,
        image: "https://via.placeholder.com/300",
        price: 132000,
        title: "Apple MacBook Air M2",
        description: "13.6-inch Liquid Retina, M2 chip, 16GB RAM, 512GB SSD.",
        rating: 4.9,
        reviews: 5200,
        link: "#",
    },
    {
        id: 10,
        image: "https://via.placeholder.com/300",
        price: 105000,
        title: "Gigabyte Aero 15",
        description: "15.6-inch 4K AMOLED, Intel i7, RTX 3070, 16GB RAM, 1TB SSD.",
        rating: 4.5,
        reviews: 2800,
        link: "#",
    },
    {
        id: 11,
        image: "https://via.placeholder.com/300",
        price: 115000,
        title: "Alienware m15 R6",
        description: "15.6-inch 165Hz, Intel i7, RTX 3070, 32GB RAM, 1TB SSD.",
        rating: 4.6,
        reviews: 3500,
        link: "#",
    },
    {
        id: 12,
        image: "https://via.placeholder.com/300",
        price: 60000,
        title: "Asus VivoBook 15",
        description: "15.6-inch FHD, AMD Ryzen 5, 8GB RAM, 512GB SSD, budget-friendly.",
        rating: 4.2,
        reviews: 2400,
        link: "#",
    },
    {
        id: 13,
        image: "https://via.placeholder.com/300",
        price: 70000,
        title: "HP Pavilion Gaming",
        description: "15.6-inch 144Hz, AMD Ryzen 7, GTX 1650, 16GB RAM, 512GB SSD.",
        rating: 4.3,
        reviews: 2200,
        link: "#",
    },
    {
        id: 14,
        image: "https://via.placeholder.com/300",
        price: 89000,
        title: "Dell Inspiron 16 Plus",
        description: "16-inch 3K display, Intel i7, RTX 3050, 16GB RAM, 1TB SSD.",
        rating: 4.4,
        reviews: 2600,
        link: "#",
    },
    {
        id: 15,
        image: "https://via.placeholder.com/300",
        price: 108000,
        title: "Samsung Galaxy Book 3",
        description: "15.6-inch AMOLED, Intel i7, 16GB RAM, 512GB SSD, ultra-thin.",
        rating: 4.5,
        reviews: 2900,
        link: "#",
    },
    {
        id: 16,
        image: "https://via.placeholder.com/300",
        price: 94000,
        title: "Microsoft Surface Laptop 5",
        description: "13.5-inch PixelSense, Intel i7, 16GB RAM, 512GB SSD, touchscreen.",
        rating: 4.6,
        reviews: 3100,
        link: "#",
    },
    {
        id: 17,
        image: "https://via.placeholder.com/300",
        price: 75000,
        title: "Lenovo Legion 5",
        description: "15.6-inch 165Hz, AMD Ryzen 7, RTX 3060, 16GB RAM, 1TB SSD.",
        rating: 4.4,
        reviews: 3300,
        link: "#",
    },
    {
        id: 18,
        image: "https://via.placeholder.com/300",
        price: 112000,
        title: "Asus ZenBook 14",
        description: "14-inch OLED, Intel i7, 16GB RAM, 1TB SSD, lightweight ultrabook.",
        rating: 4.7,
        reviews: 2800,
        link: "#",
    },
    {
        id: 19,
        image: "https://via.placeholder.com/300",
        price: 99000,
        title: "Razer Blade Stealth 13",
        description: "13.3-inch 120Hz, Intel i7, GTX 1650 Ti, 16GB RAM, 512GB SSD.",
        rating: 4.5,
        reviews: 2700,
        link: "#",
    },
    {
        id: 20,
        image: "https://via.placeholder.com/300",
        price: 87000,
        title: "Acer Swift X",
        description: "14-inch FHD, AMD Ryzen 7, RTX 3050 Ti, 16GB RAM, 512GB SSD.",
        rating: 4.3,
        reviews: 2400,
        link: "#",
    }
];

const MobileProducts = [
    {
        id: 1,
        image: "https://via.placeholder.com/300",
        price: 90000,
        title: "Google Pixel 5",
        description: "6-inch OLED display, Snapdragon 765G, 8GB RAM, and 128GB storage.",
        rating: 4.3,
        reviews: 3000,
        link: "#",
    },
    {
        id: 2,
        image: "https://via.placeholder.com/300",
        price: 105000,
        title: "Samsung Galaxy S21 Ultra",
        description: "6.8-inch Dynamic AMOLED, Snapdragon 888, 12GB RAM, 256GB storage.",
        rating: 4.6,
        reviews: 5000,
        link: "#",
    },
    {
        id: 3,
        image: "https://via.placeholder.com/300",
        price: 75000,
        title: "iPhone 12",
        description: "6.1-inch Super Retina XDR, A14 Bionic, dual cameras, 128GB storage.",
        rating: 4.5,
        reviews: 4500,
        link: "#",
    },
    {
        id: 4,
        image: "https://via.placeholder.com/300",
        price: 65000,
        title: "OnePlus 9 Pro",
        description: "6.7-inch Fluid AMOLED, Snapdragon 888, 12GB RAM, 256GB storage.",
        rating: 4.4,
        reviews: 2800,
        link: "#",
    },
    {
        id: 5,
        image: "https://via.placeholder.com/300",
        price: 85000,
        title: "Xiaomi Mi 11 Ultra",
        description: "6.81-inch AMOLED, Snapdragon 888, 12GB RAM, 512GB storage.",
        rating: 4.5,
        reviews: 3200,
        link: "#",
    },
    {
        id: 6,
        image: "https://via.placeholder.com/300",
        price: 55000,
        title: "Samsung Galaxy A72",
        description: "6.7-inch Super AMOLED, Snapdragon 720G, 8GB RAM, 128GB storage.",
        rating: 4.3,
        reviews: 2500,
        link: "#",
    },
    {
        id: 7,
        image: "https://via.placeholder.com/300",
        price: 68000,
        title: "Asus ROG Phone 5",
        description: "6.78-inch AMOLED 144Hz, Snapdragon 888, 16GB RAM, 512GB storage.",
        rating: 4.7,
        reviews: 2700,
        link: "#",
    },
    {
        id: 8,
        image: "https://via.placeholder.com/300",
        price: 72000,
        title: "iPhone SE (2022)",
        description: "4.7-inch Retina, A15 Bionic, Touch ID, 128GB storage.",
        rating: 4.6,
        reviews: 3100,
        link: "#",
    },
    {
        id: 9,
        image: "https://via.placeholder.com/300",
        price: 97000,
        title: "Samsung Galaxy Z Flip 3",
        description: "6.7-inch foldable AMOLED, Snapdragon 888, 8GB RAM, 256GB storage.",
        rating: 4.4,
        reviews: 2600,
        link: "#",
    },
    {
        id: 10,
        image: "https://via.placeholder.com/300",
        price: 120000,
        title: "iPhone 13 Pro Max",
        description: "6.7-inch Super Retina XDR, A15 Bionic, ProMotion, 256GB storage.",
        rating: 4.9,
        reviews: 6000,
        link: "#",
    },
    {
        id: 11,
        image: "https://via.placeholder.com/300",
        price: 45000,
        title: "Realme GT Master Edition",
        description: "6.43-inch AMOLED, Snapdragon 778G, 8GB RAM, 128GB storage.",
        rating: 4.2,
        reviews: 2300,
        link: "#",
    },
    {
        id: 12,
        image: "https://via.placeholder.com/300",
        price: 99000,
        title: "Samsung Galaxy S22+",
        description: "6.6-inch Dynamic AMOLED, Snapdragon 8 Gen 1, 8GB RAM, 256GB storage.",
        rating: 4.7,
        reviews: 4800,
        link: "#",
    },
    {
        id: 13,
        image: "https://via.placeholder.com/300",
        price: 67000,
        title: "Xiaomi 12 Pro",
        description: "6.73-inch AMOLED, Snapdragon 8 Gen 1, 12GB RAM, 256GB storage.",
        rating: 4.6,
        reviews: 3100,
        link: "#",
    },
    {
        id: 14,
        image: "https://via.placeholder.com/300",
        price: 59000,
        title: "Vivo X70 Pro",
        description: "6.56-inch AMOLED, Dimensity 1200, 12GB RAM, 256GB storage.",
        rating: 4.3,
        reviews: 2700,
        link: "#",
    },
    {
        id: 15,
        image: "https://via.placeholder.com/300",
        price: 49000,
        title: "Oppo Reno 7 Pro",
        description: "6.55-inch AMOLED, MediaTek Dimensity 1200, 12GB RAM, 256GB storage.",
        rating: 4.2,
        reviews: 2200,
        link: "#",
    },
    {
        id: 16,
        image: "https://via.placeholder.com/300",
        price: 72000,
        title: "Google Pixel 6 Pro",
        description: "6.71-inch LTPO AMOLED, Google Tensor, 12GB RAM, 256GB storage.",
        rating: 4.8,
        reviews: 3500,
        link: "#",
    },
    {
        id: 17,
        image: "https://via.placeholder.com/300",
        price: 80000,
        title: "Samsung Galaxy Note 20 Ultra",
        description: "6.9-inch Dynamic AMOLED, Snapdragon 865+, S-Pen support, 12GB RAM.",
        rating: 4.7,
        reviews: 4000,
        link: "#",
    },
    {
        id: 18,
        image: "https://via.placeholder.com/300",
        price: 105000,
        title: "iPhone 14 Pro",
        description: "6.1-inch Super Retina XDR, A16 Bionic, Dynamic Island, 256GB storage.",
        rating: 4.9,
        reviews: 5500,
        link: "#",
    },
    {
        id: 19,
        image: "https://via.placeholder.com/300",
        price: 98000,
        title: "Samsung Galaxy Z Fold 3",
        description: "7.6-inch foldable AMOLED, Snapdragon 888, 12GB RAM, 512GB storage.",
        rating: 4.6,
        reviews: 3700,
        link: "#",
    },
    {
        id: 20,
        image: "https://via.placeholder.com/300",
        price: 87000,
        title: "OnePlus 10 Pro",
        description: "6.7-inch LTPO AMOLED, Snapdragon 8 Gen 1, 12GB RAM, 256GB storage.",
        rating: 4.5,
        reviews: 3000,
        link: "#",
    }
];

const TabletProducts = [
    {
        id: 1,
        image: "https://via.placeholder.com/300",
        price: 65000,
        title: "Apple iPad Pro 11",
        description: "11-inch Liquid Retina display, M1 chip, 8GB RAM, 128GB storage.",
        rating: 4.7,
        reviews: 4000,
        link: "#",
    },
    {
        id: 2,
        image: "https://via.placeholder.com/300",
        price: 85000,
        title: "Samsung Galaxy Tab S7+",
        description: "12.4-inch Super AMOLED, Snapdragon 865+, S-Pen, 8GB RAM, 256GB storage.",
        rating: 4.6,
        reviews: 3200,
        link: "#",
    },
    {
        id: 3,
        image: "https://via.placeholder.com/300",
        price: 55000,
        title: "Microsoft Surface Pro 7",
        description: "12.3-inch touchscreen, Intel Core i5, 8GB RAM, 128GB SSD, detachable keyboard.",
        rating: 4.4,
        reviews: 2700,
        link: "#",
    },
    {
        id: 4,
        image: "https://via.placeholder.com/300",
        price: 45000,
        title: "Samsung Galaxy Tab A8",
        description: "10.5-inch TFT LCD, Unisoc T618, 4GB RAM, 64GB storage.",
        rating: 4.3,
        reviews: 2300,
        link: "#",
    },
    {
        id: 5,
        image: "https://via.placeholder.com/300",
        price: 99000,
        title: "Apple iPad Pro 12.9 (2022)",
        description: "12.9-inch Liquid Retina XDR, M2 chip, 16GB RAM, 512GB storage.",
        rating: 4.9,
        reviews: 5200,
        link: "#",
    },
    {
        id: 6,
        image: "https://via.placeholder.com/300",
        price: 68000,
        title: "Lenovo Tab P12 Pro",
        description: "12.6-inch AMOLED, Snapdragon 870, 8GB RAM, 256GB storage.",
        rating: 4.5,
        reviews: 2900,
        link: "#",
    },
    {
        id: 7,
        image: "https://via.placeholder.com/300",
        price: 72000,
        title: "Huawei MatePad Pro",
        description: "12.6-inch OLED, Kirin 9000E, 8GB RAM, 256GB storage.",
        rating: 4.6,
        reviews: 3100,
        link: "#",
    },
    {
        id: 8,
        image: "https://via.placeholder.com/300",
        price: 36000,
        title: "Xiaomi Pad 5",
        description: "11-inch LCD 120Hz, Snapdragon 860, 6GB RAM, 128GB storage.",
        rating: 4.4,
        reviews: 2500,
        link: "#",
    },
    {
        id: 9,
        image: "https://via.placeholder.com/300",
        price: 52000,
        title: "Samsung Galaxy Tab S6 Lite",
        description: "10.4-inch TFT LCD, Exynos 9611, 4GB RAM, 128GB storage, S-Pen.",
        rating: 4.3,
        reviews: 2200,
        link: "#",
    },
    {
        id: 10,
        image: "https://via.placeholder.com/300",
        price: 85000,
        title: "Apple iPad Air (2022)",
        description: "10.9-inch Liquid Retina, M1 chip, 8GB RAM, 256GB storage.",
        rating: 4.8,
        reviews: 4600,
        link: "#",
    },
    {
        id: 11,
        image: "https://via.placeholder.com/300",
        price: 30000,
        title: "Amazon Fire HD 10 Plus",
        description: "10.1-inch IPS LCD, Mediatek MT8183, 4GB RAM, 64GB storage.",
        rating: 4.2,
        reviews: 1900,
        link: "#",
    },
    {
        id: 12,
        image: "https://via.placeholder.com/300",
        price: 48000,
        title: "Lenovo Yoga Tab 11",
        description: "11-inch IPS LCD, MediaTek Helio G90T, 6GB RAM, 128GB storage.",
        rating: 4.3,
        reviews: 2100,
        link: "#",
    },
    {
        id: 13,
        image: "https://via.placeholder.com/300",
        price: 72000,
        title: "Microsoft Surface Go 3",
        description: "10.5-inch touchscreen, Intel Pentium Gold, 8GB RAM, 128GB SSD.",
        rating: 4.2,
        reviews: 2000,
        link: "#",
    },
    {
        id: 14,
        image: "https://via.placeholder.com/300",
        price: 54000,
        title: "Samsung Galaxy Tab S5e",
        description: "10.5-inch Super AMOLED, Snapdragon 670, 6GB RAM, 128GB storage.",
        rating: 4.4,
        reviews: 2400,
        link: "#",
    },
    {
        id: 15,
        image: "https://via.placeholder.com/300",
        price: 60000,
        title: "iPad Mini (2021)",
        description: "8.3-inch Liquid Retina, A15 Bionic, 6GB RAM, 256GB storage.",
        rating: 4.7,
        reviews: 3700,
        link: "#",
    },
    {
        id: 16,
        image: "https://via.placeholder.com/300",
        price: 39000,
        title: "Nokia T20 Tablet",
        description: "10.4-inch LCD, Unisoc T610, 4GB RAM, 64GB storage.",
        rating: 4.2,
        reviews: 1800,
        link: "#",
    },
    {
        id: 17,
        image: "https://via.placeholder.com/300",
        price: 44000,
        title: "Realme Pad X",
        description: "10.95-inch LCD, Snapdragon 695, 6GB RAM, 128GB storage.",
        rating: 4.3,
        reviews: 2000,
        link: "#",
    },
    {
        id: 18,
        image: "https://via.placeholder.com/300",
        price: 89000,
        title: "Samsung Galaxy Tab S8 Ultra",
        description: "14.6-inch Super AMOLED, Snapdragon 8 Gen 1, 12GB RAM, 512GB storage.",
        rating: 4.8,
        reviews: 4100,
        link: "#",
    },
    {
        id: 19,
        image: "https://via.placeholder.com/300",
        price: 72000,
        title: "Huawei MatePad 11",
        description: "11-inch IPS LCD 120Hz, Snapdragon 865, 8GB RAM, 256GB storage.",
        rating: 4.5,
        reviews: 2600,
        link: "#",
    },
    {
        id: 20,
        image: "https://via.placeholder.com/300",
        price: 35000,
        title: "Teclast T40 Pro",
        description: "10.4-inch IPS LCD, Unisoc T618, 8GB RAM, 128GB storage.",
        rating: 4.1,
        reviews: 1500,
        link: "#",
    }
];

export{LaptopProducts, MobileProducts, TabletProducts};
